language: java
dist: trusty
cache:
  directories:
  - "$HOME/.gradle"
matrix:
  include:
  - os: linux
    jdk: oraclejdk8
    env:
    - PUBLISH_USER=xenit
    before_install:
    - chmod +x ./gradlew
    script:
    - "./gradlew publish"
env:
  global:
  - secure: xRrtFzSKd6OgWiy4B7EvWF/1BeSmd2EiVwA2mA2lyLrMAVk0r4dVuGHzVmVZGOGkbctI3fkn1SP+8t2IHLHT4u5v0TIUvoIC5upbizvmYnNcthfL3tokrnmE+2cenAEOb98ZkM0Ng/xi3BxUBnUEhnD3bXc+WMDntCoHhacUMtPDqkZqbUSi8eH+ackhadVy5NTeKGRFitLNthF4XpE7H5HhmPNiAR/DyLp1hT0SylvkFfIQlOXpyvB+4iFxIYl+oD5xbEXwHbsFTvuGNT4OqYTLVJReuqDCkEGFszEJ4v93+aJld0scbWYv0NIfvIspc0+uCYWvo5gl+u/dhVpU2g3A7JPwx1H0vw9fcAu/Bd+yjj9QeOR79adVL8CqWmznjwhbkP5ZFFXg5rKlGsBn6H1POKlABP3qrWmK7IT9aP4zZ/XDND2LgH01oV9VvDOwzvn46pRfHH1KVM8Drd538L2uSQqkImbMfVeZ1wlxVio4p+eZbFsQ6MS/KiOv2a0Yjmy+iitAhA7GgHkzf2Wu9C3+ZDrdnDD4HCsul7NqC7yaFtBVcw1iGMNHDmKHixtKiAiebDBzawciaxaqHadu5SurC1E68gROgGshprBjhP3iIK8ljuW08OIEfmGv0Ob5YMjIM1Z27l7JlUqdcTssh1uhQSXRQsW19smpaJogFqc=
before_install:
- openssl aes-256-cbc -K $encrypted_c6215021d27f_key -iv $encrypted_c6215021d27f_iv
  -in secring.gpg.enc -out secring.gpg -d
